### ISSUE TITLE
npm run build:frontend issues

### ISSUE THREAD

**Issue by craigjam** [amazon-connect/video-call-escalation#7]
Encountered a number of issues trying to npm run build:frontend
1) react-is dependency not installed in agent-app:
```
ERROR in ./node_modules/styled-components/dist/styled-components.browser.esm.js 1:0-73
Module not found: Error: Can't resolve 'react-is' in 'C:\Users\crijm\Documents\code\video-call-escalation\agent-app\node_modules\styled-components\di
st'
resolve 'react-is' in 'C:\Users\crijm\Documents\code\video-call-escalation\agent-app\node_modules\styled-components\dist'

```
resolved by running in agent-app directory:
npm install react-is

2) Browserslist: caniuse-lite is outdated

```
> demo-website@1.0.0 build
> NODE_ENV=production webpack --config=webpack.config.prod.js --mode=production

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\util\createHash.js:
145:18)
    at BulkUpdateDecorator.update (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\util\createHash.js:46:50
)
    at RawSource.updateHash (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack-sources\lib\RawSource.js:70:8)
    at NormalModule._initBuildHash (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:888:17)
    at handleParseResult (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:954:10)
    at C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:1048:4
    at processResult (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:763:11)
    at C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:827:5
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```

resolved by running  in demo-website directory
npx browserslist@latest --update-db

3) Unsupported SSL in node v17
```
> demo-website@1.0.0 build
> NODE_ENV=production webpack --config=webpack.config.prod.js --mode=production

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\util\createHash.js:
145:18)
    at BulkUpdateDecorator.update (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\util\createHash.js:46:50
)
    at RawSource.updateHash (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack-sources\lib\RawSource.js:70:8)
    at NormalModule._initBuildHash (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:888:17)
    at handleParseResult (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:954:10)
    at C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:1048:4
    at processResult (C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:763:11)
    at C:\Users\crijm\Documents\code\video-call-escalation\demo-website\node_modules\webpack\lib\NormalModule.js:827:5
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
```

resolved by setting
export NODE_OPTIONS=--openssl-legacy-provider

**Comment by bgrove01** [comment]
I ran into the same problem with item 1, thank you for the fix, that worked for me too.

**Comment by davelemons** [comment]
I wasn't able to reproduce with latest release (2.3.1) Please open back up if you are still having issues with latest release
